name: publish yardoc for main onto gh-pages
on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write

jobs:
  yardoc:
    runs-on: ubuntu-latest
    name: "Build & push yardoc"

    steps:
      - name: Setup Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install YARD
        run: |
          gem install yard -v 0.9.28 --no-document
      - name: Checkout main to /main
        uses: actions/checkout@v3
        with:
          path: 'main'
      - name: Checkout gh-pages to /gh-pages
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
      - name: Generate docs from /main into /gh-pages
        run: |
          cd main && yard doc --output-dir ../gh-pages --no-progress
      - name: Commit & push the changes in /gh-pages
        run: |
          cd gh-pages
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'milkshake@github.local'
          COMMIT_MESSAGE=$'Update documentation to ${{ github.sha }}\n\nCo-authored-by: ${{ github.event.head_commit.author.email }}'
          git add -A .
          git commit -am "$COMMIT_MESSAGE"
          git push origin gh-pages
